### ISSUE TITLE
Compiler panic; 1.37.0-nightly (2887008e0 2019-06-12) running on x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by ndokmai** [oezgurmakkurt/blasoxide#6]
Hello,

I'm trying to build the project with rustc 1.37.0-nightly (2887008e0 2019-06-12) but I get the following error upon running `cargo +nightly build`. My CPU is Intel i7-6700. I'm not sure if the error stems from the compiler or the project's codes, so I want to post it here first. Please let me know if you think this is the compiler's fault so I can file a bug report.

```
   Compiling blasoxide v0.3.2 (/home/ndokmai/workspace/blasoxide)
thread 'rustc' panicked at 'Forcing query with already existing DepNode.
- query-key: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: All, def_id: None }, value: (Const { ty: [u32; 2], val: ByRef(AllocId(556).0x0, Allocation { bytes: [0, 0, 0, 0, 1, 0, 0, 0], relocations: Relocations(SortedMap { data: [] }), undef_mask: UndefMask { blocks: [255], len: Size { raw: 8 } }, align: Align { pow2: 2 }, mutability: Immutable, extra: () }) }, field[0]) }
- dep-node: const_field(67586bc8d6719bbd-8210aca0f024cb22)', src/librustc/ty/query/plumbing.rs:547:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.37.0-nightly (2887008e0 2019-06-12) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `blasoxide`.

To learn more, run the command again with --verbose.
```
Here is the backtrace:

```
   0:     0x7fbcc3b1e17b - backtrace::backtrace::libunwind::trace::h37e8a367d6921aa8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1:     0x7fbcc3b1e17b - backtrace::backtrace::trace_unsynchronized::h248427898d35c0c6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2:     0x7fbcc3b1e17b - std::sys_common::backtrace::_print::he196ebe73104e0d6
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x7fbcc3b1e17b - std::sys_common::backtrace::print::hea7e6b9f756deddc
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x7fbcc3b1e17b - std::panicking::default_hook::{{closure}}::hdb08e9c6d066c960
                               at src/libstd/panicking.rs:198
   5:     0x7fbcc3b1de7c - std::panicking::default_hook::h0cb542c8a02e7512
                               at src/libstd/panicking.rs:212
   6:     0x7fbcc1077dc1 - rustc::util::common::panic_hook::h67a2c98f5569bf9a
   7:     0x7fbcc3b1e9d9 - std::panicking::rust_panic_with_hook::h48a72e8eabfd4099
                               at src/libstd/panicking.rs:479
   8:     0x7fbcc3b1e472 - std::panicking::continue_panic_fmt::heb88cccc99bfebb4
                               at src/libstd/panicking.rs:382
   9:     0x7fbcc3b1e3bf - std::panicking::begin_panic_fmt::h922b3fb55ded3330
                               at src/libstd/panicking.rs:337
  10:     0x7fbcb8db690c - rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query::hcdeda713291fb756
  11:     0x7fbcb8e12b3d - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::hf0ac1774e19051a7
  12:     0x7fbcb8d6eb6d - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::hb1ee54bbccc84fa2
  13:     0x7fbcb8e47db2 - rustc_codegen_ssa::mir::constant::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::simd_shuffle_indices::h96a56ba604cad0b1
  14:     0x7fbcb8e11c90 - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h883907a69cd30e78
  15:     0x7fbcb8d6c141 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h5e43cba1539eaa67
  16:     0x7fbcb8e409a1 - rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<Bx>>::codegen_terminator::h6e3757e1505e4c92
  17:     0x7fbcb8e3b8f7 - rustc_codegen_ssa::mir::codegen_mir::he98075a486430623
  18:     0x7fbcb8e221b6 - rustc_codegen_ssa::base::codegen_instance::h1b73db7b19165b1c
  19:     0x7fbcb8d4e923 - <rustc::mir::mono::MonoItem as rustc_codegen_ssa::mono_item::MonoItemExt>::define::h623d14962de1b444
  20:     0x7fbcb8cdc4f9 - rustc_codegen_llvm::base::compile_codegen_unit::module_codegen::he5fcad9eb95a2266
  21:     0x7fbcb8d1a9dc - rustc::dep_graph::graph::DepGraph::with_task::hb0e94d730cd6a05c
  22:     0x7fbcb8cdc2d2 - rustc_codegen_llvm::base::compile_codegen_unit::h2ad715a0aef024e0
  23:     0x7fbcb8e206e3 - rustc_codegen_ssa::base::codegen_crate::hfdaed1402ad68023
  24:     0x7fbcb8e1cf9a - <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate::h23f713a56fcceb32
  25:     0x7fbcc2d58c37 - rustc::util::common::time::hfa32f21224be889a
  26:     0x7fbcc2d02deb - rustc_interface::passes::start_codegen::h80bf438f8735df80
  27:     0x7fbcc2cea2e7 - rustc::ty::context::tls::enter_global::he211de32835ffe44
  28:     0x7fbcc2d035f1 - rustc_interface::passes::BoxedGlobalCtxt::access::{{closure}}::h7b2f233b97aa10e2
  29:     0x7fbcc2d5f615 - rustc_interface::passes::create_global_ctxt::{{closure}}::h9455f3a1e30caa2a
  30:     0x7fbcc2d02146 - rustc_interface::passes::BoxedGlobalCtxt::enter::ha258207a0780f622
  31:     0x7fbcc2ced210 - rustc_interface::queries::Query<T>::compute::h504685bad686b04e
  32:     0x7fbcc2dd5cc4 - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::ongoing_codegen::h20e17154d5c23647
  33:     0x7fbcc3e13390 - rustc_interface::interface::run_compiler_in_existing_thread_pool::hedff5ce402a7589b
  34:     0x7fbcc3e82ef6 - std::thread::local::LocalKey<T>::with::hee79a74ddae74b29
  35:     0x7fbcc3e1cb65 - scoped_tls::ScopedKey<T>::set::hf6d1a699be191084
  36:     0x7fbcc3e4ebc4 - syntax::with_globals::h494bae12626463ee
  37:     0x7fbcc3e6d83d - std::sys_common::backtrace::__rust_begin_short_backtrace::heb8c4d6cac19380a
  38:     0x7fbcc3b2f8ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  39:     0x7fbcc3dfa089 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5cf9b9633bf8fcbc
  40:     0x7fbcc3b01edf - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbbe4b50e56f896eb
                               at /rustc/2887008e0ce0824be4e0e9562c22ea397b165c97/src/liballoc/boxed.rs:746
  41:     0x7fbcc3b2e5a0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h7ab4448ee8ad917c
                               at /rustc/2887008e0ce0824be4e0e9562c22ea397b165c97/src/liballoc/boxed.rs:746
  42:     0x7fbcc3b2e5a0 - std::sys_common::thread::start_thread::h0cd07c3bb37a8763
                               at src/libstd/sys_common/thread.rs:13
  43:     0x7fbcc3b2e5a0 - std::sys::unix::thread::Thread::new::thread_start::h6a06e7fee86bebc7
                               at src/libstd/sys/unix/thread.rs:79
  44:     0x7fbcc389e6db - start_thread
  45:     0x7fbcc31bb88f - __clone
  46:                0x0 - <unknown>
```

**Comment by oezgurmakkurt** [comment]
Hi, thanks for your interest

I am getting the same error with: cargo 1.37.0-nightly (545f35425 2019-05-23) on windows

This is weird since I can run `cargo +nightly bench` without problems but `cargo +nightly build`
fails with the error message you posted.

I think this is a compiler error. I don't do any sophisticated or new things in code. Maybe someone that understands this error can help.

I am developing on windows with latest stable rustc and ci is set up with stable rustc on linux so there should be no problem on those platforms.

**Comment by oezgurmakkurt** [comment]
I found this similar issue [https://github.com/rust-lang/rls/issues/999](https://github.com/rust-lang/rls/issues/999)

**Comment by oezgurmakkurt** [comment]
Also out of topic but It would be great if you could share the benchmark results on your cpu

**Comment by ndokmai** [comment]
Here are the benchmark results running with `RUSTFLAGS="-C target-cpu=native" cargo +nightly bench` on Intel i7-6700:

```
     Running target/release/deps/l3d-6621258ed4ba0014

running 1 test
test bench_dgemm ... bench:  16,481,250 ns/iter (+/- 874,206)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured; 0 filtered out

     Running target/release/deps/l3s-b0154f22c83c668d

running 4 tests
test bench_sgemm_1000 ... bench:   8,579,752 ns/iter (+/- 604,010)
test bench_sgemm_2000 ... bench:  56,040,853 ns/iter (+/- 1,110,819)
test bench_sgemm_250  ... bench:     344,293 ns/iter (+/- 96,362)
test bench_sgemm_500  ... bench:   1,070,824 ns/iter (+/- 9,854)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured; 0 filtered out
```

**Comment by oezgurmakkurt** [comment]
thanks, that looks great. I think that should be close to OpenBLAS

**Comment by ndokmai** [comment]
It's close but not quite there yet. Here's a comparison with OpenBLAS:

```
running 2 tests
test fma::common::tests::test_hadd_pd ... ignored
test fma::common::tests::test_hadd_ps ... ignored

test result: ok. 0 passed; 0 failed; 2 ignored; 0 measured; 0 filtered out

     Running target/release/deps/l3d-627e7191d60db3ff

running 1 test
test bench_dgemm ... bench:  16,018,047 ns/iter (+/- 499,212)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured; 0 filtered out

     Running target/release/deps/l3d_openblas-ea689ed0c90632c9

running 1 test
test bench_dgemm_openblas ... bench:  12,904,908 ns/iter (+/- 137,110)

test result: ok. 0 passed; 0 failed; 0 ignored; 1 measured; 0 filtered out

     Running target/release/deps/l3s-65f80de9e948a184

running 4 tests
test bench_sgemm_1000 ... bench:   8,554,702 ns/iter (+/- 249,918)
test bench_sgemm_2000 ... bench:  60,024,979 ns/iter (+/- 1,170,630)
test bench_sgemm_250  ... bench:     370,705 ns/iter (+/- 117,589)
test bench_sgemm_500  ... bench:   1,037,161 ns/iter (+/- 11,081)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured; 0 filtered out

     Running target/release/deps/l3s_openblas-57681c43a52e18a8

running 4 tests
test bench_sgemm_1000_openblas ... bench:   6,257,565 ns/iter (+/- 90,510)
test bench_sgemm_2000_openblas ... bench:  46,050,357 ns/iter (+/- 630,044)
test bench_sgemm_250_openblas  ... bench:     187,779 ns/iter (+/- 1,320)
test bench_sgemm_500_openblas  ... bench:     934,542 ns/iter (+/- 16,066)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured; 0 filtered out
```

**Comment by ndokmai** [comment]
Okay, to circle back to the main topic, I just found a work around. The problem is with incremental compilation causing the issue. If you build with the `--release` flag or with 
```
[profile.dev]
incremental = false
```
in `Cargo.toml` then the project compiles.

**Comment by oezgurmakkurt** [comment]
I think the performance difference is due to L2 cache size difference, block sizes are optimized for my cpu which has 2MB L2 cache but 4 core i7 cpus have 1MB of L2 cache so I think changing the block sizes should resolve this issue (blasoxide has the exact same performance or faster on my cpu), I want to rewrite the whole library soon to introduce a Context struct to manage block sizes and clean the code so it runs slightly better.

I am reopening this because I think this shouldn't need configuration to compile on any circumstance.

**Comment by ndokmai** [comment]
I tried it just now but there are no performance gains for these tweaks.

**Comment by oezgurmakkurt** [comment]
Ok thanks for testing, i opened #8 for this issue. I will be working on this.

**Comment by oezgurmakkurt** [comment]
this doesn't happen anymore since the whole library is reset

**Comment by oezgurmakkurt** [comment]
I added nightly to ci and it seems to work without any problems now, so I'm closing this.
